version: "3.6"

services:
  db:
    image: mysql:5
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: todo_laravel
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

volumes:
  db-data:
    external: false
